version: '3.7'

services:
  bookstore-web:
    image: acme/bookstore-web:latest
    container_name: bookstore-web
    build:
      context: ../../../
      dockerfile: angular/Dockerfile.local
    ports:
      - "4200:80"
    depends_on:
      - bookstore-api
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json
    networks:
      - abp-network

  bookstore-api:
    image: acme/bookstore-api:latest
    container_name: bookstore-api
    hostname: bookstore-api
    build:
      context: ../../
      dockerfile: src/Acme.Bookstore.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=91f91912-5ab0-49df-8166-23377efaf3cc
      - App__SelfUrl=https://localhost:44354
      - App__AngularUrl=http://localhost:4200
      - App__HealthCheckUrl=http://bookstore-api/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__SetSelfAsIssuer=true
      - AuthServer__Authority=http://bookstore-api
      - App__MVCPublicUrl=https://localhost:44306
      - ConnectionStrings__Default=mongodb://mongodb/Bookstore
      - Redis__Configuration=redis
    ports:
      - "44354:443"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy  
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  

  db-migrator:
    image: acme/bookstore-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/Bookstore.DbMigrator/Dockerfile.local
    environment:
      - ConnectionStrings__Default=mongodb://mongodb/Bookstore
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - abp-network    
  
  mongodb:
    container_name: mongodb
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
       - mongodb_data:/data/db
    networks:
      - abp-network
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 10    
  
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network  
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      

volumes:
  mongodb_data:
    name: bookstore_mongodb_data  
networks:
  abp-network:
    name: bookstore-network
    driver: bridge